import Logo from './Logo.jsx'

export default function Footer() {
  return (
    <footer className="footer">
      <div className="container">
        <Logo size="sm" />
        <div className="footer-text">
          Predictions generated by a statistical model. Not financial or betting advice.
          <br />
          <a href="https://scoreanalyticspredictions.com" target="_blank" rel="noreferrer">
            scoreanalyticspredictions.com
          </a>
        </div>
      </div>
    </footer>
  )
}
